version: 2

#sphinx:
#    builder: html
#    configuration: pyatoa/docs/conf.py

python:
    version: 3.6
    install:
        - requirements: docs/requirements_dev.txt
        - method: setuptools
          path: .

conda:
    environment: docs/environment.yml